default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Password123@!
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: demo_multiple_database
